@startuml
entity AnidoptUser {}
entity Animal {}
entity AnimalColour {}
entity AnimalColourLink {}
entity Breed {}
entity Descriptor {}
entity DescriptorLink {}
entity DescriptorType {}
entity Estimation {}
entity Organisation {}
entity Picture {}
entity Sex {}
entity Species {}
entity UserOrganisationLink {}

AnidoptUser ||--o{ UserOrganisationLink
UserOrganisationLink }o--|| Organisation
Animal -- Breed
Animal }o-- Sex
Species ||--|{ Breed
Organisation ||--|{ Animal
AnimalColour ||--o{ AnimalColourLink
Animal ||--o{ AnimalColourLink
Picture }o--|| Animal
DescriptorType ||--o{ DescriptorLink
DescriptorLink ||--|| Descriptor
DescriptorLink }o--|| Animal
@enduml
