@startuml
@startmindmap
+ Animals
++_ Type
++_ Name
++_ Age
++_ Size
++_ Gender
++_ Colour
++_ Description
-- Organisations
---_ Name
---_ Other details
-- Characteristics
---_ Name
---_ Description
-- Medicals
---_ Name
---_ Description
@endmindmap
@enduml
